version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kaifee@1
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: "no"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    volumes:
      - ./:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
